[tool.robotpy]

robotpy_version = "2025.2.1.3"

robotpy_extras = [
    "all",
    "apriltag",
    "commands2",
    "cscore",
    "navx",
    "pathplannerlib",
    "rev",
    "romi",
    "sim",
    "xrp",
    "phoenix5",
]

requires = [
    "numpy",
    "phoenix6",
]